package com.example.util

import com.example.model.AppLanguage

object AppStrings {

    fun get(key: String, language: AppLanguage): String {
        val map = if (language == AppLanguage.PERSIAN) FA else EN
        return map[key] ?: EN[key] ?: key
    }

    private val FA = mapOf(
        "app_name" to "پولیار",
        "home" to "پیشخوان",
        "transactions" to "تراکنش‌ها",
        "accounts" to "حساب‌ها",
        "debts_checks" to "طلب و چک",
        "budgets" to "بودجه‌بندی",
        "more" to "بیشتر",
        "recurring" to "تراکنش‌های دوره‌ای",
        "quick_add" to "ثبت سریع تراکنش",
        "save_transaction" to "ثبت تراکنش",
        "cancel" to "انصراف",
        "confirm" to "تأیید",
        "close" to "بستن",
        "delete" to "حذف",
        "edit" to "ویرایش",
        "search_hint" to "جستجو در توضیحات، طرف حساب، دسته‌بندی...",
        "expense" to "هزینه",
        "income" to "درآمد",
        "transfer" to "انتقال داخلی",
        "amount" to "مبلغ",
        "source_account" to "حساب مبدا",
        "dest_account" to "حساب مقصد",
        "category" to "دسته‌بندی",
        "description" to "توضیحات یا بابت",
        "contact_person" to "طرف حساب / فروشگاه",
        "date" to "تاریخ",
        "total_net_worth" to "مجموع دارایی خالص",
        "monthly_income" to "درآمد ماه",
        "monthly_expense" to "هزینه ماه",
        "monthly_net_savings" to "پس‌انداز خالص",
        "expense_breakdown" to "تفکیک و تحلیل هزینه‌ها",
        "recent_transactions" to "آخرین تراکنش‌ها",
        "view_all" to "مشاهده همه",
        "no_transactions_yet" to "هنوز هیچ تراکنشی ثبت نشده است",
        "no_accounts_yet" to "هنوز حسابی اضافه نکرده‌اید",
        "no_budgets_yet" to "هنوز هیچ بودجه‌ای برای این ماه تعریف نشده است",
        "no_debts_yet" to "هیچ بدهی یا طلبی ثبت نشده است",
        "no_checks_yet" to "هیچ چکی ثبت نشده است",
        "settings_title" to "تنظیمات و سفارشی‌سازی",
        "theme_mode" to "تم برنامه (حالت شب و روز)",
        "language_region" to "زبان و تنظیمات منطقه‌ای",
        "app_language" to "زبان برنامه",
        "calendar_system" to "نوع تقویم",
        "date_format" to "فرمت نمایش تاریخ",
        "digit_format" to "نوع ارقام اعداد",
        "first_day_of_week" to "اولین روز هفته",
        "time_format" to "فرمت نمایش ساعت",
        "currency_unit" to "واحد پول نمایشی",
        "security_privacy" to "امنیت و حریم خصوصی",
        "app_lock_pin" to "قفل برنامه با پین‌کد",
        "set_pin" to "تنظیم پین‌کد",
        "backup_restore" to "پشتیبان‌گیری و بازیابی",
        "export_backup" to "پشتیبان‌گیری از کل داده‌ها (JSON)",
        "restore_backup" to "بازیابی نسخه پشتیبان",
        "export_csv" to "خروجی اکسل و CSV",
        "about_pooleyar" to "درباره پولیار",
        "about_desc" to "نسخه ۲.۰ — پولیار سامانه هوشمند مدیریت مالی شخصی بهینه‌سازی‌شده برای تبلت و موبایل با پشتیبانی کامل از استانداردهای بانکی و تقویم ایران.",
        "add_account" to "افزودن حساب جدید",
        "edit_account" to "ویرایش حساب",
        "account_name" to "نام حساب",
        "account_type" to "نوع حساب",
        "bank_name" to "بانک",
        "card_number" to "شماره کارت",
        "sheba_number" to "شماره شبا",
        "initial_balance" to "موجودی اولیه",
        "current_balance" to "موجودی کنونی",
        "add_custom_bank" to "افزودن بانک دلخواه",
        "bank_title_input" to "نام بانک یا مؤسسه مالی",
        "select_bank" to "انتخاب بانک",
        "bank_account" to "حساب بانکی",
        "cash_wallet" to "کیف پول نقدی",
        "savings" to "صندوق پس‌انداز",
        "i_owe" to "بدهی من به دیگران",
        "owed_to_me" to "طلب من از دیگران",
        "due_date" to "تاریخ سررسید",
        "total_amount" to "کل مبلغ",
        "remaining_amount" to "مانده بدهی/طلب",
        "add_debt" to "ثبت بدهی یا طلب",
        "edit_debt" to "ویرایش بدهی یا طلب",
        "pay_repay" to "پرداخت و تسویه",
        "fully_settled" to "کامل تسویه شده",
        "check_incoming" to "چک دریافتی",
        "check_outgoing" to "چک صادره",
        "check_number" to "شماره یا شناسه صیادی",
        "add_check" to "ثبت چک جدید",
        "edit_check" to "ویرایش چک",
        "clear_check" to "پاس شدن و ثبت در حساب",
        "cleared" to "پاس شده و ثبت در حساب",
        "all" to "همه",
        "expenses" to "هزینه‌ها",
        "incomes" to "درآمدها",
        "transfers" to "انتقال‌ها",
        "budget_limit" to "سقف بودجه",
        "budget_spent" to "مصرف شده",
        "budget_remaining" to "باقیمانده",
        "budget_exceeded" to "بیش از حد مجاز خرج شده!",
        "add_budget" to "تعیین سقف بودجه",
        "edit_budget" to "ویرایش بودجه",
        "recurring_title" to "عنوان دوره",
        "recurring_frequency" to "فاصله تکرار",
        "day_of_month" to "روز موعد در هر ماه",
        "add_recurring" to "تعریف تراکنش دوره‌ای جدید",
        "save_recurring" to "ثبت دوره",
        "recurring_title_hint" to "عنوان (مثلاً اجاره خانه، واریز حقوق)",
        "invalid_amount_error" to "لطفاً مبلغ معتبری وارد کنید",
        "select_account_error" to "لطفاً حساب مبدا را انتخاب کنید",
        "transfer_same_account_error" to "حساب مبدا و مقصد نمی‌تواند یکسان باشد",
        "account_name_error" to "لطفاً نام حساب را وارد کنید",
        "manage_accounts_subtitle" to "مدیریت حساب‌های بانکی، کارت‌ها و کیف‌های پول نقدی"
    )

    private val EN = mapOf(
        "app_name" to "Pooleyar",
        "home" to "Dashboard",
        "transactions" to "Transactions",
        "accounts" to "Accounts",
        "debts_checks" to "Debts & Checks",
        "budgets" to "Budgets",
        "more" to "More",
        "recurring" to "Recurring",
        "quick_add" to "Quick Add",
        "save_transaction" to "Save Transaction",
        "cancel" to "Cancel",
        "confirm" to "Confirm",
        "close" to "Close",
        "delete" to "Delete",
        "edit" to "Edit",
        "search_hint" to "Search descriptions, contacts, categories...",
        "expense" to "Expense",
        "income" to "Income",
        "transfer" to "Transfer",
        "amount" to "Amount",
        "source_account" to "Source Account",
        "dest_account" to "Destination Account",
        "category" to "Category",
        "description" to "Description",
        "contact_person" to "Contact / Merchant",
        "date" to "Date",
        "total_net_worth" to "Total Net Worth",
        "monthly_income" to "Monthly Income",
        "monthly_expense" to "Monthly Expense",
        "monthly_net_savings" to "Net Savings",
        "expense_breakdown" to "Expense Breakdown",
        "recent_transactions" to "Recent Transactions",
        "view_all" to "View All",
        "no_transactions_yet" to "No transactions recorded yet",
        "no_accounts_yet" to "No accounts added yet",
        "no_budgets_yet" to "No budgets configured for this month",
        "no_debts_yet" to "No debts or receivables recorded",
        "no_checks_yet" to "No checks recorded",
        "settings_title" to "Settings & Preferences",
        "theme_mode" to "App Theme (Day / Night)",
        "language_region" to "Language & Region",
        "app_language" to "Application Language",
        "calendar_system" to "Calendar System",
        "date_format" to "Date Format",
        "digit_format" to "Numeral Digits",
        "first_day_of_week" to "First Day of Week",
        "time_format" to "Time Format",
        "currency_unit" to "Display Currency",
        "security_privacy" to "Security & Privacy",
        "app_lock_pin" to "App Lock PIN",
        "set_pin" to "Configure PIN",
        "backup_restore" to "Backup & Restore",
        "export_backup" to "Export Complete Backup (JSON)",
        "restore_backup" to "Restore Backup File",
        "export_csv" to "Export Transactions to CSV",
        "about_pooleyar" to "About Pooleyar",
        "about_desc" to "Version 2.0 — Pooleyar is a premier personal finance suite optimized for Samsung tablets and phones, featuring offline persistence and full regional customizations.",
        "add_account" to "Add New Account",
        "edit_account" to "Edit Account",
        "account_name" to "Account Name",
        "account_type" to "Account Type",
        "bank_name" to "Bank",
        "card_number" to "Card Number",
        "sheba_number" to "IBAN / Sheba",
        "initial_balance" to "Opening Balance",
        "current_balance" to "Current Balance",
        "add_custom_bank" to "Add Custom Bank",
        "bank_title_input" to "Bank / Institution Name",
        "select_bank" to "Select Bank",
        "bank_account" to "Bank Account",
        "cash_wallet" to "Cash Wallet",
        "savings" to "Savings Fund",
        "i_owe" to "Money I Owe",
        "owed_to_me" to "Money Owed to Me",
        "due_date" to "Due Date",
        "total_amount" to "Total Amount",
        "remaining_amount" to "Remaining Amount",
        "add_debt" to "Add Debt / Receivable",
        "edit_debt" to "Edit Debt / Receivable",
        "pay_repay" to "Pay / Settle",
        "fully_settled" to "Fully Settled",
        "check_incoming" to "Incoming Check",
        "check_outgoing" to "Outgoing Check",
        "check_number" to "Check / Sayad Number",
        "add_check" to "Add Check",
        "edit_check" to "Edit Check",
        "clear_check" to "Clear & Record in Account",
        "cleared" to "Cleared & Account Updated",
        "all" to "All",
        "expenses" to "Expenses",
        "incomes" to "Incomes",
        "transfers" to "Transfers",
        "budget_limit" to "Budget Limit",
        "budget_spent" to "Spent",
        "budget_remaining" to "Remaining",
        "budget_exceeded" to "Budget Exceeded!",
        "add_budget" to "Set Monthly Budget",
        "edit_budget" to "Edit Budget",
        "recurring_title" to "Recurring Title",
        "recurring_frequency" to "Frequency",
        "day_of_month" to "Day of Month",
        "add_recurring" to "Add Recurring Transaction",
        "save_recurring" to "Save Recurring",
        "recurring_title_hint" to "Title (e.g. Rent, Salary)",
        "invalid_amount_error" to "Please enter a valid amount",
        "select_account_error" to "Please select a source account",
        "transfer_same_account_error" to "Source and destination accounts must be different",
        "account_name_error" to "Please enter account name",
        "manage_accounts_subtitle" to "Manage bank accounts, credit cards, and cash wallets"
    )
}
